//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSaleDistribute.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebSaleDistribute.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting User Name.
        /// </summary>
        public static string AccountingUserName {
            get {
                return ResourceManager.GetString("AccountingUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Doc Serial No.
        /// </summary>
        public static string BusinessDocSerialNo {
            get {
                return ResourceManager.GetString("BusinessDocSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Doc Status Name.
        /// </summary>
        public static string BusinessDocStatusName {
            get {
                return ResourceManager.GetString("BusinessDocStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counting No.
        /// </summary>
        public static string CountingNo {
            get {
                return ResourceManager.GetString("CountingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counting Register Date.
        /// </summary>
        public static string CountingRegDate {
            get {
                return ResourceManager.GetString("CountingRegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer ID.
        /// </summary>
        public static string CustomerID {
            get {
                return ResourceManager.GetString("CustomerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute Date.
        /// </summary>
        public static string DistributeDate {
            get {
                return ResourceManager.GetString("DistributeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor ID.
        /// </summary>
        public static string DistributorEmployeeID {
            get {
                return ResourceManager.GetString("DistributorEmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor Name.
        /// </summary>
        public static string DistributorEmployeeName {
            get {
                return ResourceManager.GetString("DistributorEmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee ID.
        /// </summary>
        public static string EmployeeID {
            get {
                return ResourceManager.GetString("EmployeeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Remain.
        /// </summary>
        public static string InvoiceRemain {
            get {
                return ResourceManager.GetString("InvoiceRemain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Weight.
        /// </summary>
        public static string NetWeight {
            get {
                return ResourceManager.GetString("NetWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string NominalCode {
            get {
                return ResourceManager.GetString("NominalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payable.
        /// </summary>
        public static string Payable {
            get {
                return ResourceManager.GetString("Payable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perosn ID.
        /// </summary>
        public static string PersonID {
            get {
                return ResourceManager.GetString("PersonID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Name.
        /// </summary>
        public static string PersonName {
            get {
                return ResourceManager.GetString("PersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price ID.
        /// </summary>
        public static string PriceID {
            get {
                return ResourceManager.GetString("PriceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ProductDescription {
            get {
                return ResourceManager.GetString("ProductDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason ID.
        /// </summary>
        public static string ReasonID {
            get {
                return ResourceManager.GetString("ReasonID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Name.
        /// </summary>
        public static string ReasonName {
            get {
                return ResourceManager.GetString("ReasonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Date.
        /// </summary>
        public static string RegDate {
            get {
                return ResourceManager.GetString("RegDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Returned Amount.
        /// </summary>
        public static string ReturnedAmount {
            get {
                return ResourceManager.GetString("ReturnedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial No.
        /// </summary>
        public static string ReturnedBusinessDocSerialNo {
            get {
                return ResourceManager.GetString("ReturnedBusinessDocSerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Sale Price.
        /// </summary>
        public static string SalePrice {
            get {
                return ResourceManager.GetString("SalePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jalali Date Difference.
        /// </summary>
        public static string ShamsiDateDiff {
            get {
                return ResourceManager.GetString("ShamsiDateDiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut Code.
        /// </summary>
        public static string Shortcut {
            get {
                return ResourceManager.GetString("Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores IDs.
        /// </summary>
        public static string StoreIDs {
            get {
                return ResourceManager.GetString("StoreIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores Name.
        /// </summary>
        public static string StoreNames {
            get {
                return ResourceManager.GetString("StoreNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit ID.
        /// </summary>
        public static string UnitID {
            get {
                return ResourceManager.GetString("UnitID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Carton on Hand.
        /// </summary>
        public static string WarehouseCartonOnHand {
            get {
                return ResourceManager.GetString("WarehouseCartonOnHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Order No.
        /// </summary>
        public static string WarehouseOrderNo {
            get {
                return ResourceManager.GetString("WarehouseOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouse Packet on Hand.
        /// </summary>
        public static string WarehousePacketOnHand {
            get {
                return ResourceManager.GetString("WarehousePacketOnHand", resourceCulture);
            }
        }
    }
}
