IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QR_Codes]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[QR_Codes](
	[output_tkey] [int] NOT NULL,
	[qrText] [nvarchar](4000) NOT NULL,
	[qrImage] [image] NULL,
 CONSTRAINT [PK_QR_Codes] PRIMARY KEY CLUSTERED 
(
	[output_tkey] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END